### ISSUE TITLE
CoreDX with ParticipantQoS

### ISSUE THREAD

**Issue by marianneR** [SEDS/CUTS#1]
I am able to get the ParticipantQoS working with the rtidds and opensplice middleware but cannot get communication to occur when using coredx middleware.

Using the HelloWorld example and adding the ParticipantQoS as provided in the https://github.com/SEDS/CUTS/blob/master/tests/iccm/opensplice/ParticipantQoS/descriptors/ReceiverQoS.dpd and https://github.com/SEDS/CUTS/blob/master/tests/iccm/opensplice/ParticipantQoS/descriptors/SenderQoS.dpd files the Sender is sending messages but the Receiver never receives the coredx messages.

CoreDX will communicate if the QoS is not used, but in this case the message topic is <greeting> a global topic that will be sent and received by all instances of the Sender and Receiver components. For our test environment we need "isprivate" topics and to be able to assign a topic name where required in the system. 

Is it possible that QoS specified in the .dpd files for opensplice/ParticipantQoS are not supported in coredx?

Could an example ParticipantQoS be provided for CoreDX?
Regards,
Marianne.

**Comment by tmpeiris** [comment]
I am looking at this issue. I am trying to catchup CUTS CoreDx stuff as I haven't worked on this part of CUTS. I will study your issue and in connect with you soon.

**Comment by tmpeiris** [comment]
Is it possible for you to send any stack trace or error messages related to the problem ? Is it crashing ?

**Comment by marianneR** [comment]
@tmpeiris  There are no error messages and the execution does not crash. 

The problem is that the receiver will not receive messages if the Quality of Service dose not match on both sides of the connection (ie both publisher and subscriber) . I have attempted to use the ParticipantQoS as provided in %CUTS_ROOT%\tests\iccm\opensplice\ParticipantQoS\descriptors\ *QoS.dpd files. These files do not work with CoreDX.

My question is, can you provide an example of the *QoS.dpd files that will work with CoreDX?

If you need more information, I will have time to try a few more test cases using CoreDX on Monday.

**Comment by tmpeiris** [comment]
I need to study more on CoreDx and to see how we have to specify QoS. Righnow when I use the QoS.dpd files of OpenSplice with CoreDX it is crashing. Because it doesn't seem to crash in your setup can you send me the descriptor files. Are you trying to run the same iCCM CoreDx HelloWorld example with QoS, or do you have any other modifications ?

**Comment by marianneR** [comment]
@tmpeiris  I have emailed the CoreDX model and files I am using to test the ParticipantQoS, (have tested on CentOS and Windows7)

Two modifications I made to the generated files;
1) added print out of message recieved in the HelloReceiverImpl.cpp file
      ACE_DEBUG ((LM_DEBUG, ACE_TEXT ("Receiver content = %s\n"), ev->content ()));
2) changed the HelloWorld.cdp file to to correct location for the svnt 
     <location>HelloWorld_Components_svnt</location>
    (the values in the ParticipantQoS.xme model are incorrect for the ImplementationArtifacts, so the cdp file generated from the GME interpreter is also incorrect)

I also modified the run_test.pl script to use coredx.locality.config

CentOS test;
When I execute the model with perl run_test.pl, I can see dds messages are being sent with the following details.
 topic: HelloWorld_ComponentImplementations_HelloWorld_asm_HelloWorld_asm_Sender_TOPIC_NAME_OVERRIDE
 type: Message
Messages never received in the Receiver component.

Windows7 test;
Crashes when trying to configure_publisher from in CoreDX_Servant.cpp

If the ReceiverQoS.dpd and the SenderQoS.dpd files are removed or renamed, the execution will output the messages received by the Receiver component.

Hope this helps solve the QoS issue.

**Comment by tmpeiris** [comment]
Thanks I am looking into this.

**Comment by tmpeiris** [comment]
It seems like the "partition" QoS parameter in Publisher/Subscriber is causing the isssue. If you comment out,

partition
      name
        item A item
      name
 partition

(The XML tags are removed as this doesn't show it properly with tags)
in the publisher section and in the subscriber section in QoS files it works. Are you using that QoS parameter for anything ?

**Comment by marianneR** [comment]
We are not using most of the QoS, except for controlling the topic name. 
I will try removing the partition tag, and run a few test cases on Monday.

**Comment by marianneR** [comment]
Have tested on CentOS and Windows, to verify if removing the partition works;
    <partition>
      <name>
        <item>A</item>
      </name>
    </partition> 
This fix will allow Windows to execute without crashing.

This fix will NOT receive messages sent through the CoreDX middleware.

**Comment by tmpeiris** [comment]
So are you saying it is working correctly in Windows and not in CentOS ?

**Comment by marianneR** [comment]
No, it is still not working correctly.
a) Windows executed without crashing (with the partition it crashes), but it did not receive any messages sent via CoreDX middleware.
b) Centos operated the same as before, it did not receive any messages sent via CoreDX middleware.

Have you been able to receive messages using CoreDX with the ParticipantQoS .dpd file ?

**Comment by tmpeiris** [comment]
It seems like one of the connections is missing in your HelloWorld.cdp file. When I have added the following missing connection it worked in my Windows 7.

<connection>
 <name>HelloWorld.ComponentImplementations.HelloWorld_asm.HelloWorld_asm.Sender.messenger_object::HelloWorld.ComponentImplementations.HelloWorld_asm.HelloWorld_asm.Receiver.echo</name>
    <internalEndpoint>
      <portName>messenger_object</portName>
      <provider>false</provider>
      <kind>SimplexReceptacle</kind>
      <instance xmi:idref="_138A3272-267D-11E1-8000-000C29A84559"/>
    </internalEndpoint>
    <internalEndpoint>
      <portName>echo</portName>
      <provider>true</provider>
      <kind>Facet</kind>
      <instance xmi:idref="_187CFE54-267D-11E1-8000-000C29A84559"/>
    </internalEndpoint>
  </connection>

**Comment by marianneR** [comment]
The model that I am using does not contain messenger_obj or echo and dose not need that connection. Maybe you are using a different model ?
Since you have a working model, can you email to me that model and generated files along with the dpd ParticipantQoS?

**Comment by tmpeiris** [comment]
I simply added QoS to the HelloWorld example of iCCM CoreDX example, which is found here.

https://github.com/SEDS/CUTS/tree/master/examples/iccm/HelloWorld/coredx

So I think the model it is using should be

https://github.com/SEDS/CUTS/blob/master/examples/iccm/HelloWorld/models/HelloWorld.xme

So what you can do is, you can first try the HelloWorld example after specifying QoS. If it working, you can generate the descriptor files for the model and try again. If that is not woeking we may need to update the model.

**Comment by tmpeiris** [comment]
The CoreDx HelloWolrd example currently in CUTS with the participant QoS files you sent me is working after commenting out the partition QoS element.

**Comment by marianneR** [comment]
I have again tested your example code in 
https://github.com/SEDS/CUTS/tree/master/examples/iccm/HelloWorld/coredx
With participant QoS files, and HelloWorld.cdp containing link to the QoS files.
The output is like;
Sender: Pushing greeting
Sender: Greeting event sent
Sender: Incrementing count on messenger_object
Receiver: Facet Request increment count = 1
Sender: Count incremented

The output that indicates that the CoreDX message is received should be;
Receiver InputAction Effect for content = Hello, World!, count = 1

The "Receiver InputAction" output is not seen when using the Participant QoS. Therefore the InputAction in the Receiver is never receiving messages via CoreDX middleware. 

Please confirm if you are getting the "Receiver InputAction" output to verify that your example is working.

**Comment by tmpeiris** [comment]
Yeah you are correct, I will look into this.

**Comment by tmpeiris** [comment]
I was able to get the sample working by commenting out the latency_buget QoS policy inside the datawriter. The default value for latency_buget duration is 0, so by setting it to 0(In the datawriter) also we can get it to work. Please read section 12.3.8 of the following manual and see whether you want to increase the duration value.
http://www.twinoakscomputing.com/documents/CoreDX_DDS_Programmers_Guide_v3.6.pdf

Most applications work with the default value, and it is useful only when you have publisher, which is publishing at a very high data rate.

**Comment by marianneR** [comment]
Thanks, the QoS for CoreDX is working for me on CentOS and Windows7.

So for CoreDX the QoS will not work if using the partition tag and the latency_buget duration.

This should not be an issue for us for the immediate future.
