### ISSUE TITLE
Building CUTS on Windows with Visual Studio 2012

### ISSUE THREAD

**Issue by marianneR** [SEDS/CUTS#2]
I have downloaded and installed CoreDX 3.6.25 for a Windows 32bit VM using Visual Studio 2012
When the default.features has coredx=1 the build of the CUTS.sln will produce the following errors.

------ Build started: Project: iCCM_CoreDX_svnt, Configuration: Debug Win32 ------
  CoreDX.cpp
c:\coredx\coredx-3.6.25-evaluation\target\include\dds\toc_util.h(59): error C2011: 'timespec' : 'struct' type redefinition
          c:\cuts\middleware\ace\ace\os_include\os_time.h(59) : see declaration of 'timespec'
  CoreDX_Servant.cpp
c:\coredx\coredx-3.6.25-evaluation\target\include\dds\toc_util.h(59): error C2011: 'timespec' : 'struct' type redefinition
          c:\cuts\middleware\ace\ace\os_include\os_time.h(59) : see declaration of 'timespec'
  Generating Code...
------ Build started: Project: iCCM_CoreDX_Deployment_Handlers, Configuration: Debug Win32 ------
  CoreDX_Component_Instance_Handler.cpp
c:\coredx\coredx-3.6.25-evaluation\target\include\dds\toc_util.h(59): error C2011: 'timespec' : 'struct' type redefinition
          c:\cuts\middleware\ace\ace\os_include\os_time.h(59) : see declaration of 'timespec'
  CoreDX_Container.cpp
c:\coredx\coredx-3.6.25-evaluation\target\include\dds\toc_util.h(59): error C2011: 'timespec' : 'struct' type redefinition
          c:\cuts\middleware\ace\ace\os_include\os_time.h(59) : see declaration of 'timespec'
  CoreDX_Container_Strategy.cpp
c:\coredx\coredx-3.6.25-evaluation\target\include\dds\toc_util.h(59): error C2011: 'timespec' : 'struct' type redefinition
          c:\cuts\middleware\ace\ace\os_include\os_time.h(59) : see declaration of 'timespec'
  Generating Code...

**Comment by marianneR** [comment]
This problem may be fixed in CoreDX. I notified them of the problem and it has been on their "back burner for several weeks". They will send me an update when they have a fix for this problem.

**Comment by tmpeiris** [comment]
The only way to fix this right now is to comment out the timespec struct in CoreDx. You can comment out following part in coredx-3.6.25-Evaluation\target\include\dds\toc_util.h (lines 59-62)

/_struct timespec {
    long         tv_sec;
    int          tv_nsec;
  };_/

This won't affect CUTS iCCM stuff as for now, because we are not using it inside CUTS. However if you are using it you may have to find an alternative solution.
